import java.awt.Image;
import java.awt.Toolkit;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class perpus extends javax.swing.JFrame {
    public void Kosongkan_Form(){
        txtkode.setEditable(true);//primary key
        txtkode.setText(null);
         txtpengarang.setText(null);
          txtjudul.setText(null);
           txttahun.setText(null);
            txtpenerbit.setText(null);
             
    }
    public void Tampilkan_Data(){
        DefaultTableModel model=new DefaultTableModel();
        model.addColumn("nomor");
        model.addColumn("kode");
        model.addColumn("judul_buku");
        model.addColumn("pengarang");
        model.addColumn("Penerbit");
        model.addColumn("tahun_terbit");
        try{
            int no=1;
            
    String sql="select*from data_buku where kode like '%"
            +txtcari.getText()+"%'" + "or judul_buku like '%"
            +txtcari.getText()+"%'"+ "or pengarang like '%"+txtcari.getText()+"%'"+ "or penerbit like '%"+txtcari.getText()+"%'"+ 
            "or tahun_terbit like '%"+txtcari.getText()+"%'";;
            
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
          java.sql.ResultSet res=stm.executeQuery(sql);
          
          while (res.next()){
              //DefaultTableModel model=new DefaultTableModel();
              model.addRow(new Object[]{no++, res.getString(1), res.getString(2), res.getString(3), res.getString(4),res.getString(5)});
                tabperpustakaan.setModel(model);
          }
//          tabperpustakaan.setModel(model);

            
        }catch (SQLException e){
          System.out.println("eror: "+ e.getMessage());
        }

    }     
          

    /**
     * Creates new form perpus
     */
    public perpus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtpenerbit = new javax.swing.JTextField();
        txtkode = new javax.swing.JTextField();
        txtjudul = new javax.swing.JTextField();
        txtpengarang = new javax.swing.JTextField();
        txttahun = new javax.swing.JTextField();
        btncancel = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        btnsearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabperpustakaan = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        btndelete = new javax.swing.JButton();
        txtcari = new javax.swing.JTextField();
        btnexit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Kode Buku");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Penerbit");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Pengarang");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Judul Buku");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, -1));
        jPanel1.add(txtpenerbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, 406, 29));
        jPanel1.add(txtkode, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 406, 29));
        jPanel1.add(txtjudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 406, 29));
        jPanel1.add(txtpengarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 230, 406, 29));
        jPanel1.add(txttahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, 406, 29));

        btncancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btncancel.setText("cancel");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });
        jPanel1.add(btncancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 320, -1, -1));

        btnedit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnedit.setText("edit");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });
        jPanel1.add(btnedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 250, 93, -1));

        btnsave.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnsave.setText("save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 250, 93, -1));

        btnsearch.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnsearch.setText("search");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 600, -1, -1));

        tabperpustakaan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "kode", "judul_buku", "pengarang", "penerbit", "tahun_terbit"
            }
        ));
        tabperpustakaan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabperpustakaanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabperpustakaan);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 949, 153));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tahun Penerbit");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, -1, -1));

        btndelete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btndelete.setText("delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 320, 93, -1));
        jPanel1.add(txtcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 600, 406, 29));

        btnexit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnexit.setText("exit");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });
        jPanel1.add(btnexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 600, 93, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("Refresh data");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 600, -1, -1));

        jLabel1.setBackground(new java.awt.Color(153, 153, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Data Buku Perpustkaan Politeknik Kampar");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 700, 40));

        jButton2.setBackground(new java.awt.Color(102, 102, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Do you play Game??");
        jButton2.setActionCommand("game");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bc buku.jpg"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1628, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 761, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
try{
    String sql="insert into data_buku values('"+txtkode.getText()+"','"+txtjudul.getText()
            +"','"+ txtpengarang.getText()+"','"
            +txtpenerbit.getText()+"','"+txttahun.getText()+"')";
    java.sql.Connection conn=(Connection)Koneksi.configDB();
    java.sql.PreparedStatement pstm=conn.prepareStatement(sql);
    pstm.execute();
//while(pstm.execute()){
    JOptionPane.showMessageDialog(null,"proses simpan berhasil");
   Tampilkan_Data();
//}
//    JOptionPane.showMessageDialog(null,"proses simpan berhasil");
//   Tampilkan_Data();
  //Kosongkan_Form();

}catch (HeadlessException | SQLException e){
    JOptionPane.showMessageDialog(this, e.getMessage());
}       
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
try{
    String sql="update data_buku set kode='"+txtkode.getText()+"',judul_buku='"+txtjudul.getText()
            +"',pengarang'"+ txtpengarang.getText()+"',penerbit'"
            +txtpenerbit.getText()+"',tahun_terbit'"+txttahun.getText()+"' where kode='"+txtkode.getText()+"'";
            
    java.sql.Connection conn=(Connection)Koneksi.configDB();
    java.sql.PreparedStatement pstm=conn.prepareStatement(sql);
    pstm.execute();
    JOptionPane.showMessageDialog(null,"Edit data berhasil....");
   Tampilkan_Data();
   //Kosongkan_Form();

}catch (HeadlessException | SQLException e){
    JOptionPane.showMessageDialog(this, e.getMessage());
}
        // TODO add your handling code here:
    }//GEN-LAST:event_btneditActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
Kosongkan_Form();
        // TODO add your handling code here:
    }//GEN-LAST:event_btncancelActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
try{
    String sql="delete from data_buku where kode='"+txtkode.getText()+"'";         
    java.sql.Connection conn=(Connection)Koneksi.configDB();
    java.sql.PreparedStatement pstm=conn.prepareStatement(sql);
    pstm.execute();
    JOptionPane.showMessageDialog(null,"Hapus data berhasil....");
   Tampilkan_Data();
   //Kosongkan_Form();

}catch (HeadlessException | SQLException e){
    JOptionPane.showMessageDialog(this, e.getMessage());
}

    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnexitActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
try{//untuk menjalankan sebuah blok program 
    String sql="select*from data_buku where kode like'%"
            +txtcari.getText()+"%'" + "or judul_buku like '%"
            +txtcari.getText()+"%'"+ "or pengarang like '%"+txtcari.getText()+"%'"+ "or penerbit like '%"+txtcari.getText()+"%'"+ 
            "or tahun_terbit like '%"+txtcari.getText()+"%'";
            
    java.sql.Connection conn=(Connection)Koneksi.configDB();
    java.sql.PreparedStatement pstm=conn.prepareStatement(sql);
    pstm.executeQuery();
   // JOptionPane.showMessageDialog(null,"pencarian selesai....");
   Tampilkan_Data();
   //Kosongkan_Form();

}

catch (HeadlessException | SQLException e){
    JOptionPane.showMessageDialog(this, e.getMessage());
}
        // TODO add your handling code here:
                                           

        // TODO add your handling code here:
    }//GEN-LAST:event_btnsearchActionPerformed

    private void tabperpustakaanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabperpustakaanMouseClicked
        int baris=tabperpustakaan.rowAtPoint(evt.getPoint());

        String kode=tabperpustakaan.getValueAt(baris, 1).toString();
        txtkode.setText(kode);

        String judul=tabperpustakaan.getValueAt(baris, 2).toString();
        txtjudul.setText(judul);

        String pengarang=tabperpustakaan.getValueAt(baris, 3).toString();
        txtpengarang.setText(pengarang);

        String penerbit=tabperpustakaan.getValueAt(baris, 4).toString();
        txtpenerbit.setText(penerbit);

        String tahun=tabperpustakaan.getValueAt(baris, 5).toString();
        txttahun.setText(tahun);
        // TODO add your handling code here:
    }//GEN-LAST:event_tabperpustakaanMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try{
    String sql="select*from data_buku where kode like'%"
            +txtcari.getText()+"%'" + "or judul_buku like '%"
            +txtcari.getText()+"%'"+ "or pengarang like '%"+txtcari.getText()+"%'"+ "or penerbit like '%"+txtcari.getText()+"%'"+ 
            "or tahun_terbit like '%"+txtcari.getText()+"%'";
            
    java.sql.Connection conn=(Connection)Koneksi.configDB();
    java.sql.PreparedStatement pstm=conn.prepareStatement(sql);
    pstm.executeQuery();
    
        
    
    JOptionPane.showMessageDialog(null,"refresh complete....");
   Tampilkan_Data();
   //Kosongkan_Form();

}

catch (HeadlessException | SQLException e){
    JOptionPane.showMessageDialog(this, e.getMessage());
}
        // TODO add your handling code here:
                                           


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
this.dispose();
new game().setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(perpus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(perpus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(perpus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(perpus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new perpus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabperpustakaan;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtjudul;
    private javax.swing.JTextField txtkode;
    private javax.swing.JTextField txtpenerbit;
    private javax.swing.JTextField txtpengarang;
    private javax.swing.JTextField txttahun;
    // End of variables declaration//GEN-END:variables
}
