
import java.util.logging.Level;//untuk mengontrol output logging logger
import java.util.logging.Logger;//untuk membuat type data BigDecimal
import javax.swing.JFrame;//untuk memanggil library swing
import javax.swing.JOptionPane;//untuk mengambil dan menampilkan informasi

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class splashnya extends javax.swing.JFrame {

    /**
     * Creates new form splashnya
     */
    public splashnya() {
         /*this.setExtendedState(JFrame.MAXIMIZED_BOTH); 
        this.setUndecorated(true);*/
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        latar = new javax.swing.JPanel();
        loadd = new javax.swing.JProgressBar();
        tampilan_loadd = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 0));

        latar.setBackground(new java.awt.Color(255, 255, 255));
        latar.setMaximumSize(new java.awt.Dimension(900, 500));
        latar.setMinimumSize(new java.awt.Dimension(900, 500));
        latar.setPreferredSize(new java.awt.Dimension(900, 500));
        latar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        latar.add(loadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, 900, -1));

        tampilan_loadd.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tampilan_loadd.setText("loadingg....");
        latar.add(tampilan_loadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, -1, -1));

        jLabel1.setText("0%");
        latar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 420, 70, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spls.jpg"))); // NOI18N
        latar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(latar, javax.swing.GroupLayout.PREFERRED_SIZE, 1371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(latar, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public void splsh(){
        this.dispose();
        new akun().setVisible(true);
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(splashnya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(splashnya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(splashnya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(splashnya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        splashnya sk = new splashnya();
        sk.setVisible(true);
        try {
            for(int i=0;i<=100;i++){
            Thread.sleep(100);
            sk.jLabel1.setText(i+"%");
            if(i==10){
                sk.tampilan_loadd.setText("turn on loading.....");
            }
             if(i==100){
                sk.tampilan_loadd.setText("loading selesai.....");
            }
            sk.loadd.setValue(i);
            }
        } 
        catch (Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        /*catch (InterruptedException ex) {
            Logger.getLogger(splashnya.class.getName()).log(Level.SEVERE, null, ex);
        }*/
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new splashnya().setVisible(false);
                sk.splsh();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel latar;
    private javax.swing.JProgressBar loadd;
    private javax.swing.JLabel tampilan_loadd;
    // End of variables declaration//GEN-END:variables
}
